keys:
  - &lowgain age1ggj2sk4ce77t7slcaahxa84u0ng7x9yu9w5aqepplrmfxmu7vg2sn990rw
  # - &fridge exampleagefromsshhostkey
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
        - *lowgain
#   - path_regex: secrets/fridge.yaml$
#     key_groups:
#       - age:
#         - *lowgain
